### ISSUE TITLE
Dependencies Issue

### ISSUE THREAD

**Issue by NoahZinsmeister** [MetaMask/json-rpc-engine#10]
The following "dependencies" should be reclassified as "devDependencies", as they are causing errors in upstream packages.

```
"@babel/preset-env": "^7.3.4"
"babelify": "^10.0.0"
```

Error example: `... json-rpc-engine > @babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".`

**Comment by kumavis** [comment]
browserify transforms like `babelify` need to be deps and not dev deps. However, im considering removing the browserify transform because the babelify/babel version change has been an endless headache

**Comment by NoahZinsmeister** [comment]
i'm pretty sure this package is the one causing some very obscure babel-related build errors in some of my projects.

i'm a bit confused, why can't you just build your source files locally and distribute the built files? having any babel-related package as a dependency is a recipe for disaster imo.

**Comment by kumavis** [comment]
@NoahZinsmeister can you link to the relevant errors

**Comment by spalladino** [comment]
We have a similar situation, in that we are getting all of babel installed along with our package ([zos](https://github.com/zeppelinos/zos), a command-line tool) since we indirectly depend on this package. We'd expect babel to be required only as a dev dependency.

Funny thing, we noticed this when core-js (a dependency of Babel) [added a post-install message asking for a job for its maintainer](https://github.com/zloirock/core-js/issues/548).

**Comment by NoahZinsmeister** [comment]
The warnings are thrown any time a package depends on `json-rpc-engine` without having babel as a dependency, which again should absolutely not be a requirement and is bad practice :).

Code shipped in packages should run without compilation/transpilation/whatever in all environments that the author is interested in supporting (for example, ES5 as described in #3).

```
warning "@walletconnect/web3-subprovider > web3-provider-engine > eth-json-rpc-filters > json-rpc-engine > @babel/preset-env@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@walletconnect/web3-subprovider > web3-provider-engine > eth-json-rpc-filters > json-rpc-engine > babelify@10.0.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "@walletconnect/web3-subprovider > web3-provider-engine > eth-json-rpc-filters > json-rpc-engine > @babel/preset-env > @babel/plugin-transform-template-literals@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".
```

**Comment by rekmarks** [comment]
@NoahZinsmeister this should be merged soon: https://github.com/MetaMask/json-rpc-engine/pull/17

**Comment by NoahZinsmeister** [comment]
thanks @rekmarks ! you're a champ
