### ISSUE TITLE
remove unused dependencies

### ISSUE THREAD

**Issue by drortirosh** [MetaMask/json-rpc-engine#110]
"dependencies" currently contains "babel-preset-env" and "babelify"

afaik, they are used only during build, and thus can be moved into devDependency, and not clutter the client's tree.

**Comment by mcmire** [comment]
Did you mean to report this for a different package? This package doesn't rely (directly or indirectly) on `babel-preset-env` or `babelify`: http://npm.anvaka.com/#/view/2d/json-rpc-engine

**Comment by mcmire** [comment]
Closing due to lack of response, but happy to reconsider.
