### ISSUE TITLE
Use `@metamask/utils` for types

### ISSUE THREAD

**Issue by mcmire** [MetaMask/json-rpc-engine#119]
`@metamask/utils` now houses most of the types from this package (`JsonRpcRequest`, `JsonRpcResponse`, and the like). The only thing that we haven't brought over yet is `PendingJsonRpcResponse` (this issue is tracked in https://github.com/MetaMask/utils/issues/39). Once this is moved over, we can remove the types from this package and import them from `@metamask/utils`.

**Comment by FrederikBolding** [comment]
Done!
