### ISSUE TITLE
NPM releases 

### ISSUE THREAD

**Issue by GregTheGreek** [MetaMask/json-rpc-engine#22]
It seems that npm releases aren't generating a build. After a fresh `npm install` my directory (`node_modules/json-rpc-engine`) doesn't contain a build or lib as per the documentation.
```
node_modules/json-rpc-engine
├── CHANGELOG.md
├── README.md
├── package.json
├── src
│   ├── asMiddleware.js
│   ├── createAsyncMiddleware.js
│   ├── createScaffoldMiddleware.js
│   ├── getUniqueId.js
│   ├── idRemapMiddleware.js
│   ├── index.d.ts
│   ├── index.js
│   └── mergeMiddleware.js
└── test
    ├── asMiddleware.spec.js
    ├── basic.spec.js
    ├── createAsyncMiddleware.spec.js
    ├── idRemapMiddleware.spec.js
    └── mergeMiddleware.spec.js
```

**Comment by rekmarks** [comment]
This package has been migrated to TypeScript, and I believe this issue is no longer relevant. Sorry for the delay, and let me know if the issue is not resolved.

**Comment by GregTheGreek** [comment]
daaaaaaamn lol this is an old one

**Comment by rekmarks** [comment]
Well, the distribution of this package should be working just fine now! 😂
