### ISSUE TITLE
Incorrect error code for undefined method

### ISSUE THREAD

**Issue by bitpshr** [MetaMask/json-rpc-engine#6]
Originally posted by @Qqwy at MetaMask/metamask-extension#4693:

----

## Expected Behaviour

The call 
```javascript
web3.currentProvider.sendAsync({id: 1, method: "does_not_exist", params: []}, console.log)
```

returns 

```json
{
  "id": 1,
  "error": {
    "code": -32601,
    "message": "JSON-RPC method not found"
  }
}
```
_(obviously, the actual content string of the message field is not specified by the standard, but something akin to this would probably be the most understandable)_

## Actual Behaviour

This call returns

```json
{
  "id": 1,
  "error": {
    "code": -32603,
    "message": "Internal JSON-RPC error."
  }
}
```

This means that MetaMask (or possibly one of its dependencies) does not properly follow the [JSON-RPC Spec](https://www.jsonrpc.org/specification).

## Browser+OS used

This is using MetaMask version 4.8.0 on FireFox on Manjaro Linux, but I doubt this problem is stack-specific.

**Comment by bellaj** [comment]
in my case i was calling a function not supported by ganache 💯 
`message: 'Method shh_newSymKey not supported.',
`
